#!/bin/bash
set -eo pipefail

patch -Np0 < patches/spatialite.patch
patch -Np0 < patches/gg_dxf.h.patch
patch -Np0 < patches/gg_formats.h.patch
patch -Np0 < patches/gg_structs.h.patch
patch -Np0 < patches/sqlite.h.patch
patch -Np0 < patches/stored_procedures.c.patch
patch -Np0 < patches/configure.patch

for f in $(find spatialite -name "Makefile*"); do
  echo "Removing LOADABLE_EXTENSION: $f"
  sed -i '' 's/\-DLOADABLE_EXTENSION//g' $f
done
